# Site settings
title: Fairfax Art
email: d.fogel@comcast.net
description: "Art and Sculpture by Danielle Fogel ."
baseurl: ""
url: "http://fairfaxart.com"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
